language: c
os: linux

#sudo: false <-- deprecated

#before_install:
  #- sudo apt-get -y install zlib1g-dev

addons:
  apt:
    packages:
      - valgrind
      - zlib1g-dev
  
compiler: gcc

script:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
  
