
ex1:
	gcc -Wall -O2 -c ../circ_buf.c -o ../outputs/circ_buf.o
	gcc -Wall -O2 -c 01_ex_simple.c -o ../outputs/01_ex_simple.o -I..
	gcc ../outputs/circ_buf.o ../outputs/01_ex_simple.o -o ../outputs/01_ex_simple
	../outputs/01_ex_simple
